language: java

jdk:
  - oraclejdk8
  - openjdk11
  - oraclejdk11

script:
  - mvn clean compile exec:exec
  - rm -rf out target
  - ./gradlew clean run
  - rm -rf out target
  - ./gradlew shadowJar && java -jar build/libs/hello_vlingo.jar
