package github.dled.demo;

import io.vlingo.actors.Definition;
import io.vlingo.actors.World;

import java.util.concurrent.atomic.AtomicLong;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        final World world = World.start("playground");
        try {
            final long N = 50_000_000;

            final Greeter greeter = world.actorFor(Definition.has(ConsoleGreeter.class, Definition.NoParameters), Greeter.class);

            greeter.greet(System.getProperty("user.name"));

            greeter.startBenchmark();

            for (long i = 0; i < N; i++)
                greeter.tick();

            greeter.reportProgress();

            //for comparison, pure increment:
            java.util.concurrent.atomic.AtomicLong count=new AtomicLong();
            final Stopwatch sw = new Stopwatch();
            for (long i = 0; i < N; i++)
                count.getAndIncrement();
            sw.dumpElapsedForCount(count.get(),"simple increment");

            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        } finally {
            // waits for quiescence
            world.terminate();
        }

    }
}
