package github.dled.demo;

import io.vlingo.actors.Definition;
import io.vlingo.actors.World;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        final World world = World.start("playground");
        try {
            final Greeter greeter = world.actorFor(Definition.has(ConsoleGreeter.class, Definition.NoParameters), Greeter.class);

            greeter.greet(System.getProperty("user.name"));

            greeter.stop();
        } finally {
            world.terminate();
        }

    }
}
